/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://sketchfab.com/3d-models/neversong-peet-e5c6fcc16df340c5bc58aa100a8a6677
Title: Neversong Peet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Astronaut(props) {
  const { nodes, materials } = useGLTF('/models/neversong_peet.glb')
  const ref = useRef()
  const { scale: propScale, position: propPosition, ...rest } = props || {}
  const scale = typeof propScale === 'number' ? propScale : 0.4
  const position = Array.isArray(propPosition) ? propPosition : [1.3, -1, 0]
  return (
    <group ref={ref} {...rest} dispose={null} scale={scale} position={position}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0.geometry}
          material={materials.peete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0_1.geometry}
          material={materials.peete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0_2.geometry}
          material={materials.peete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0_3.geometry}
          material={materials.peete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0_4.geometry}
          material={materials.peete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0_5.geometry}
          material={materials.peete}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/neversong_peet.glb')
