/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallmasterr (https://sketchfab.com/wallmasterr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/neversong-peet-e5c6fcc16df340c5bc58aa100a8a6677
Title: Neversong Peetī
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/neversong_peet.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0.geometry}
          material={materials.peete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0_1.geometry}
          material={materials.peete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0_2.geometry}
          material={materials.peete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0_3.geometry}
          material={materials.peete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0_4.geometry}
          material={materials.peete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0_5.geometry}
          material={materials.peete}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/neversong_peet.glb')
